sonar.projectKey=flexo_syside
sonar.organization=openmbee
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
