name: Test sysmlv2_dls

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements-ci.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -e .
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        mkdir -p test-results
        pytest -v --tb=short \
          --junitxml=test-results/results.xml \
          --cov=src/geometry_api \
          --cov-report=xml:test-results/coverage.xml \
          --cov-report=html:test-results/htmlcov

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-sysmlv2-dls
        path: test-results/
